-- Slice 17: Training-centre ecosystem — partners, referrals, attribution, evidence, share rules, accruals.
-- Blueprint Documents 01/05/06 + Sections 30-31/36-38/42. Accruals are ledger records (ACCRUED),
-- not payouts: paid_at stays null until real payout rails exist. Historical attribution is
-- retained when partners deactivate (no cascade delete from partners to attributions).

CREATE TABLE `training_partners` (
    `id` VARCHAR(191) NOT NULL,
    `uuid` VARCHAR(191) NOT NULL,
    `legal_name` VARCHAR(191) NOT NULL,
    `display_name` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `institution_type` VARCHAR(191) NOT NULL,
    `contact_email` VARCHAR(191) NULL,
    `contact_phone` VARCHAR(191) NULL,
    `website` VARCHAR(191) NULL,
    `address_line_1` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `province` VARCHAR(191) NULL,
    `postal_code` VARCHAR(191) NULL,
    `country` VARCHAR(191) NULL DEFAULT 'ZA',
    `categories_served` JSON NULL,
    `logo_url` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    `verification_status` VARCHAR(191) NOT NULL DEFAULT 'UNVERIFIED',
    `partnership_notes` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `deleted_at` DATETIME(3) NULL,
    UNIQUE INDEX `training_partners_uuid_key`(`uuid`),
    INDEX `training_partners_status_idx`(`status`),
    INDEX `training_partners_verification_status_idx`(`verification_status`),
    INDEX `training_partners_institution_type_idx`(`institution_type`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `training_centre_users` (
    `id` VARCHAR(191) NOT NULL,
    `partner_id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `role` VARCHAR(191) NOT NULL DEFAULT 'STAFF',
    `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    UNIQUE INDEX `training_centre_users_partner_id_user_id_key`(`partner_id`, `user_id`),
    INDEX `training_centre_users_user_id_idx`(`user_id`),
    INDEX `training_centre_users_partner_id_status_idx`(`partner_id`, `status`),
    PRIMARY KEY (`id`),
    CONSTRAINT `training_centre_users_partner_id_fkey` FOREIGN KEY (`partner_id`) REFERENCES `training_partners`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `training_referrals` (
    `id` VARCHAR(191) NOT NULL,
    `partner_id` VARCHAR(191) NOT NULL,
    `code_hash` VARCHAR(191) NOT NULL,
    `code_prefix` VARCHAR(191) NOT NULL,
    `invited_email` VARCHAR(191) NULL,
    `invited_phone` VARCHAR(191) NULL,
    `programme` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    `expires_at` DATETIME(3) NOT NULL,
    `created_by` VARCHAR(191) NOT NULL,
    `claimed_by_user_id` VARCHAR(191) NULL,
    `claimed_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    UNIQUE INDEX `training_referrals_code_hash_key`(`code_hash`),
    INDEX `training_referrals_partner_id_status_idx`(`partner_id`, `status`),
    INDEX `training_referrals_status_expires_at_idx`(`status`, `expires_at`),
    INDEX `training_referrals_claimed_by_user_id_idx`(`claimed_by_user_id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `training_referrals_partner_id_fkey` FOREIGN KEY (`partner_id`) REFERENCES `training_partners`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `training_centre_providers` (
    `id` VARCHAR(191) NOT NULL,
    `partner_id` VARCHAR(191) NOT NULL,
    `provider_id` VARCHAR(191) NOT NULL,
    `referred_user_id` VARCHAR(191) NULL,
    `referral_id` VARCHAR(191) NULL,
    `source` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `referred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `approved_at` DATETIME(3) NULL,
    `ended_at` DATETIME(3) NULL,
    `ended_reason` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    UNIQUE INDEX `training_centre_providers_partner_id_provider_id_key`(`partner_id`, `provider_id`),
    INDEX `training_centre_providers_partner_id_status_idx`(`partner_id`, `status`),
    INDEX `training_centre_providers_provider_id_status_idx`(`provider_id`, `status`),
    INDEX `training_centre_providers_referral_id_idx`(`referral_id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `training_centre_providers_partner_id_fkey` FOREIGN KEY (`partner_id`) REFERENCES `training_partners`(`id`) ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `training_evidence` (
    `id` VARCHAR(191) NOT NULL,
    `partner_id` VARCHAR(191) NOT NULL,
    `provider_id` VARCHAR(191) NOT NULL,
    `attribution_id` VARCHAR(191) NULL,
    `programme` VARCHAR(191) NULL,
    `qualification_reference` VARCHAR(191) NULL,
    `institution_confirmation` TEXT NULL,
    `completion_date` DATE NULL,
    `media_asset_id` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'SUBMITTED',
    `submitted_by` VARCHAR(191) NOT NULL,
    `reviewed_by` VARCHAR(191) NULL,
    `reviewed_at` DATETIME(3) NULL,
    `review_note` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    INDEX `training_evidence_partner_id_status_idx`(`partner_id`, `status`),
    INDEX `training_evidence_provider_id_idx`(`provider_id`),
    INDEX `training_evidence_attribution_id_idx`(`attribution_id`),
    INDEX `training_evidence_media_asset_id_idx`(`media_asset_id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `training_evidence_partner_id_fkey` FOREIGN KEY (`partner_id`) REFERENCES `training_partners`(`id`) ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `partner_share_rules` (
    `id` VARCHAR(191) NOT NULL,
    `scope` VARCHAR(191) NOT NULL,
    `partner_id` VARCHAR(191) NULL,
    `programme` VARCHAR(191) NULL,
    `percent` DECIMAL(5, 2) NOT NULL,
    `currency` VARCHAR(191) NOT NULL DEFAULT 'ZAR',
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `effective_from` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `effective_to` DATETIME(3) NULL,
    `created_by` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    INDEX `partner_share_rules_scope_is_active_idx`(`scope`, `is_active`),
    INDEX `partner_share_rules_partner_id_is_active_idx`(`partner_id`, `is_active`),
    INDEX `partner_share_rules_is_active_effective_from_idx`(`is_active`, `effective_from`),
    PRIMARY KEY (`id`),
    CONSTRAINT `partner_share_rules_partner_id_fkey` FOREIGN KEY (`partner_id`) REFERENCES `training_partners`(`id`) ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `training_centre_earnings` (
    `id` VARCHAR(191) NOT NULL,
    `partner_id` VARCHAR(191) NOT NULL,
    `provider_id` VARCHAR(191) NOT NULL,
    `booking_id` VARCHAR(191) NOT NULL,
    `payment_id` VARCHAR(191) NULL,
    `gross_amount` DECIMAL(12, 2) NOT NULL,
    `commission_rate` DECIMAL(5, 2) NULL,
    `commission_amount` DECIMAL(12, 2) NULL,
    `partner_percent` DECIMAL(5, 2) NOT NULL,
    `partner_amount` DECIMAL(12, 2) NOT NULL,
    `currency` VARCHAR(191) NOT NULL DEFAULT 'ZAR',
    `rule_id` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'ACCRUED',
    `idempotency_key` VARCHAR(191) NULL,
    `earned_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `paid_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    UNIQUE INDEX `training_centre_earnings_booking_id_key`(`booking_id`),
    UNIQUE INDEX `training_centre_earnings_idempotency_key_key`(`idempotency_key`),
    INDEX `training_centre_earnings_partner_id_status_earned_at_idx`(`partner_id`, `status`, `earned_at`),
    INDEX `training_centre_earnings_provider_id_idx`(`provider_id`),
    INDEX `training_centre_earnings_booking_id_idx`(`booking_id`),
    INDEX `training_centre_earnings_status_idx`(`status`),
    PRIMARY KEY (`id`),
    CONSTRAINT `training_centre_earnings_partner_id_fkey` FOREIGN KEY (`partner_id`) REFERENCES `training_partners`(`id`) ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
